version: '3.8'
services:
  app:
    container_name: ${APP_HOST:-chat_pdf}
    build: .
    volumes:
      - ./src/:/home/app/src/
    env:
      -./.env
    depends_on:
      - ollama
      - ollama-webui
    networks:
      - public

  ollama:
    container_name: ${OLLAMA_HOST:-ollama}
    image: ollama/ollama:latest
    ports:
      - ${OLLAMA_PORT:-11434}:${OLLAMA_PORT:-11434}
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - public

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OLLAMA_WEB_PORT:-8080}:${OLLAMA_WEB_PORT:-8080}
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:${OLLAMA_PORT:-7869} #comma separated ollama hosts
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_URL=http://localhost:${OLLAMA_WEB_PORT:-8080}
      - WEBUI_SECRET_KEY=t0p-s3cr3t
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - public

networks:
  public:
    external: true

